name: Code check

permissions:
  contents: read
  pull-requests: write

on: [ pull_request ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install clippy
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: cache
        uses: Swatinem/rust-cache@v2
      - name: clippy check
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cache
        uses: Swatinem/rust-cache@v2
      - name: fmt check
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
